# 2. Linear Algebra

In [1]:
import numpy as np
import pandas as pd

import torch

## Sum

In [3]:
x = torch.arange(12).reshape((3,4))
x

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [9]:
#row sum
x.sum(axis=1)

tensor([ 6, 22, 38])

In [6]:
x.sum(axis=1, keepdims=True)

tensor([[ 6],
        [22],
        [38]])

In [10]:
#cumulative row sum
x.cumsum(axis=1)

tensor([[ 0,  1,  3,  6],
        [ 4,  9, 15, 22],
        [ 8, 17, 27, 38]])

## Element-wise Multiplication (Hadamard Product)

$$
\mathbf{A} \odot \mathbf{B} =
\begin{bmatrix}
    a_{11}  b_{11} & a_{12}  b_{12} & \dots  & a_{1n}  b_{1n} \\
    a_{21}  b_{21} & a_{22}  b_{22} & \dots  & a_{2n}  b_{2n} \\
    \vdots & \vdots & \ddots & \vdots \\
    a_{m1}  b_{m1} & a_{m2}  b_{m2} & \dots  & a_{mn}  b_{mn}
\end{bmatrix}
$$

In [33]:
x = torch.arange(4).reshape(2,2)
x

tensor([[0, 1],
        [2, 3]])

In [34]:
y = torch.arange(4,8).reshape(2,2)
y

tensor([[4, 5],
        [6, 7]])

In [35]:
x * y

tensor([[ 0,  5],
        [12, 21]])

## Vectors Dot Product

For two vectors:

$$\mathbf{x},\mathbf{y}\in\mathbb{R}^d$$

Their **dot product** is th sum of element-wise multiplication:

$$\langle\mathbf{x},\mathbf{y}\rangle = \mathbf{x}^\top \mathbf{y} = \sum_{i=1}^{d} x_i y_i$$

In [41]:
x = torch.rand(3)
x

tensor([0.4262, 0.5212, 0.2859])

In [42]:
y = torch.rand(3)
y

tensor([0.6073, 0.2379, 0.0512])

In [43]:
torch.dot(x.T, y)

tensor(0.3975)

In [44]:
torch.sum(x*y)

tensor(0.3975)

## Matrix-Vector Product

For a matrix $A$ and a vector $x$:

$$\mathbf{A} \in \mathbb{R}^{m \times n}, \mathbf{x} \in \mathbb{R}^n$$

Their matrix-vector product is a vector of dot products:

$$
\mathbf{A}\mathbf{x}
= \begin{bmatrix}
\mathbf{a}^\top_{1} \\
\mathbf{a}^\top_{2} \\
\vdots \\
\mathbf{a}^\top_m \\
\end{bmatrix}\mathbf{x}
= \begin{bmatrix}
 \mathbf{a}^\top_{1} \mathbf{x}  \\
 \mathbf{a}^\top_{2} \mathbf{x} \\
\vdots\\
 \mathbf{a}^\top_{m} \mathbf{x}\\
\end{bmatrix}.
$$

In [48]:
A = torch.randn(3,2)
A

tensor([[-1.0556,  0.8810],
        [ 2.0503, -1.3040],
        [ 0.4164,  0.9645]])

In [50]:
x = torch.randn(2)
x

tensor([-1.6025,  1.5897])

In [51]:
torch.mv(A, x)

tensor([ 3.0922, -5.3586,  0.8660])

In [56]:
torch.dot(A[0], x)

tensor(3.0922)

## Matrix-Matrix Multiplication

For two matrices $\mathbf{A} \in \mathbb{R}^{n \times k}$ and $\mathbf{B} \in \mathbb{R}^{k \times m}$：

$$
\mathbf{A}=\begin{bmatrix}
 a_{11} & a_{12} & \cdots & a_{1k} \\
 a_{21} & a_{22} & \cdots & a_{2k} \\
\vdots & \vdots & \ddots & \vdots \\
 a_{n1} & a_{n2} & \cdots & a_{nk} \\
\end{bmatrix},\quad
\mathbf{B}=\begin{bmatrix}
 b_{11} & b_{12} & \cdots & b_{1m} \\
 b_{21} & b_{22} & \cdots & b_{2m} \\
\vdots & \vdots & \ddots & \vdots \\
 b_{k1} & b_{k2} & \cdots & b_{km} \\
\end{bmatrix}
$$

which can be expressed as: 

$$
\mathbf{A}=
\begin{bmatrix}
\mathbf{a}^\top_{1} \\
\mathbf{a}^\top_{2} \\
\vdots \\
\mathbf{a}^\top_n \\
\end{bmatrix},
\quad \mathbf{B}=\begin{bmatrix}
 \mathbf{b}_{1} & \mathbf{b}_{2} & \cdots & \mathbf{b}_{m} \\
\end{bmatrix}
$$

Their matrix-matrix multiplication is a matrix of dot products:

$$
\mathbf{C} = \mathbf{AB} = \begin{bmatrix}
\mathbf{a}^\top_{1} \\
\mathbf{a}^\top_{2} \\
\vdots \\
\mathbf{a}^\top_n \\
\end{bmatrix}
\begin{bmatrix}
 \mathbf{b}_{1} & \mathbf{b}_{2} & \cdots & \mathbf{b}_{m} \\
\end{bmatrix}
= \begin{bmatrix}
\mathbf{a}^\top_{1} \mathbf{b}_1 & \mathbf{a}^\top_{1}\mathbf{b}_2& \cdots & \mathbf{a}^\top_{1} \mathbf{b}_m \\
 \mathbf{a}^\top_{2}\mathbf{b}_1 & \mathbf{a}^\top_{2} \mathbf{b}_2 & \cdots & \mathbf{a}^\top_{2} \mathbf{b}_m \\
 \vdots & \vdots & \ddots &\vdots\\
\mathbf{a}^\top_{n} \mathbf{b}_1 & \mathbf{a}^\top_{n}\mathbf{b}_2& \cdots& \mathbf{a}^\top_{n} \mathbf{b}_m
\end{bmatrix}
$$

In [58]:
A = torch.randn(3,2)
A

tensor([[-0.0525, -0.8603],
        [-0.4927, -0.6797],
        [-0.7959, -1.2185]])

In [59]:
B = torch.randn(2,3)
B

tensor([[-1.2093,  2.1007,  0.6003],
        [-0.1634, -1.3328, -0.1583]])

In [61]:
torch.mm(A, B)

tensor([[ 0.2041,  1.0363,  0.1047],
        [ 0.7069, -0.1291, -0.1881],
        [ 1.1616, -0.0480, -0.2848]])

## Norms

For a vector $x$, its norm $f(x)$ fulfills the following:

$$f(\alpha \mathbf{x}) = |\alpha| f(\mathbf{x})$$

$$f(\mathbf{x} + \mathbf{y}) \leq f(\mathbf{x}) + f(\mathbf{y})$$

$$f(\mathbf{x}) \geq 0$$

The The $L_2$ norm is given as:

**$$\|\mathbf{x}\|_2 = \sqrt{\sum_{i=1}^n x_i^2}$$**

The $L_1$ norm is given as:

$$\|\mathbf{x}\|_1 = \sum_{i=1}^n \left|x_i \right|$$

The $L_p$ norm is given as:

$$\|\mathbf{x}\|_p = \left(\sum_{i=1}^n \left|x_i \right|^p \right)^{1/p}$$

In [64]:
x = torch.randn(1,4)
x

tensor([[0.5925, 0.0059, 0.8309, 1.1607]])

In [66]:
L2_norm = torch.norm(x)
L2_norm

tensor(1.5456)

In [67]:
L1_norm = torch.abs(x).sum()
L1_norm

tensor(2.5901)

For a matrix $X$, its Frobenius norm is given as:

$$\|\mathbf{X}\|_F = \sqrt{\sum_{i=1}^m \sum_{j=1}^n x_{ij}^2}$$

In [68]:
X = torch.randn(4,3)
X

tensor([[ 0.0830, -0.2763,  1.2468],
        [-1.6291,  0.1751,  0.4190],
        [-1.4045,  1.4664, -2.1554],
        [-0.2464,  1.2471,  0.8080]])

In [69]:
torch.norm(X)

tensor(3.9415)

In [ ]:
<div>
<img src="attachment:image.png" width="600"/>
</div>